#!/usr/bin/env python
# coding: utf-8

import sys, os

def escape_shell_arg(s):
    return "'" + s.replace("'", "'\\''") + "'"

def print_err(*items):
    sys.stderr.write(' '.join(items)+'\n')

def main(argv):
	if ( len( argv ) < 2 ):
		return

	repos = {
		'wp'  : 'http://core.svn.wordpress.org/trunk/',
		'p2'  : 'http://svn.automattic.com/wpcom-themes/p2/',
	}

	if ( argv[0] not in repos ):
		return

	# Build path
	argv[-1] = repos[ argv[0] ] + argv[-1]

	os.system( 'svn blame ' + " ".join( argv[1:] ) )

if __name__ == '__main__':
	main(sys.argv[1:])